- name: Install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest
- name: start mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes
- name: setup mysql root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:password token={{ token }} url=http://vault-int.srikanth553.storee:8200') }}

