- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: Load App Pre-requisites 
  ansible.builtin.include_tasks:
    file: app_pre_setup.yml

- name: download app dependencies
  ansible.builtin.shell: mvn clean package ; mv target/${{ app_name }}-1.0.jar ${{ app_name }}.jar
  args:
    chdir: /app
  
