- name: copy service file
  ansible.builtin.copy:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/${{ app_name }}.service
    
- name: start service
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

